version: '3.8'

services:
  web-10022:
    build:
      context: .
      args:
        HTML_FILE: "三维一体交易体系 - 代码 - by Gemini - 10022.html"
    ports:
      - "10022:80"
    container_name: web-10022
    restart: unless-stopped

  web-10030:
    build:
      context: .
      args:
        HTML_FILE: "TZ交易系统-10030.html"
    ports:
      - "10030:80"
    container_name: web-10030
    restart: unless-stopped

  web-10031:
    build:
      context: .
      args:
        HTML_FILE: "Aquabridge-SGX v8.1 - 10031.html"
    ports:
      - "10031:80"
    container_name: web-10031
    restart: unless-stopped

  web-10032:
    build:
      context: .
      args:
        HTML_FILE: "薛定谔的Call主页.html"
    ports:
      - "10032:80"
    container_name: web-10032
    restart: unless-stopped

  web-10033:
    build:
      context: .
      args:
        HTML_FILE: "Aquabridge-SGX v8.1 - 10031.html"
    ports:
      - "10033:80"
    container_name: web-10033
    restart: unless-stopped